name: Build and Package GenEvolve3D Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.11'

    steps:
      - name: Clear Workspace
        run: Remove-Item -Recurse -Force .\* -Exclude .git, .github
        shell: pwsh

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create Virtual Environment
        run: python -m venv venv

      - name: Activate Virtual Environment
        run: . .\venv\Scripts\Activate  # Corrected activation command for Windows

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        working-directory: ${{ github.workspace }}
        run: |
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Find GenEvolve3D Files
        id: find_files
        run: |
          $installerFile = Get-ChildItem -Recurse -Filter 'installer.nsi' | Select-Object -First 1 -ExpandProperty FullName
          $pythonScript = Get-ChildItem -Recurse -Filter 'GenEvolve3D.py' | Select-Object -First 1 -ExpandProperty FullName
          echo "::set-output name=installerFile::$installerFile"
          echo "::set-output name=pythonScript::$pythonScript"
        shell: pwsh

      - name: Build Executable
        working-directory: ${{ github.workspace }}
        run: |
          pyinstaller --onefile --noconsole --paths src --name GenEvolve3D ${{ steps.find_files.outputs.pythonScript }}
        shell: cmd

      - name: Install NSIS
        run: choco install nsis -y

      - name: Copy NSIS Script
        run: |
          if (Test-Path -Path ${{ steps.find_files.outputs.installerFile }}) {
            Copy-Item -Path ${{ steps.find_files.outputs.installerFile }} -Destination .
          } else {
            echo "Installer script not found."
            exit 1
          }
        shell: pwsh

      - name: Package as Installer
        working-directory: ${{ github.workspace }}
        run: makensis installer.nsi
        shell: cmd

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: GenEvolve3D-Installer
          path: ./GenEvolve3D/dist/GenEvolve3D.exe
