name: Build and Package GenEvolve3D Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.11'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file
      # Add a step here to ensure that your 'src/GenEvolve3D.py' file exists and is in the correct location.

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --paths src --name GenEvolve3D src/GenEvolve3D.py
        shell: cmd

      - name: Install NSIS
        run: |
          choco install nsis -y

      - name: Package as Installer
        run: |
          cp ./GenEvolve3D/installer.nsi ${{ github.workspace }}
          makensis ${{ github.workspace }}/installer.nsi
        shell: cmd

      - name: Upload Packaged Application
        uses: actions/upload-artifact@v2
        with:
          name: GenEvolve3D-Installer
          path: ./GenEvolve3D/dist/GenEvolve3D.exe
