name: Build and Package GenEvolve3D Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.11'

    steps:
      - name: Clear Workspace
        run: Remove-Item -Recurse -Force .\* -Exclude .git, .github
        shell: pwsh

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create Virtual Environment
        run: python -m venv venv

      - name: Activate Virtual Environment
        run: . .\venv\Scripts\Activate  # Corrected activation command for Windows

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        working-directory: ${{ github.workspace }}
        run: |
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Build Executable
        working-directory: ${{ github.workspace }}
        run: |
          pyinstaller --onefile --noconsole --paths src --name GenEvolve3D src/GenEvolve3D.py
        shell: cmd

      - name: Install NSIS
        run: choco install nsis -y

      - name: Prepare NSIS Script
        working-directory: ${{ github.workspace }}
        run: cp GenEvolve3D/installer.nsi .  # Copy from GenEvolve3D directory

      - name: Package as Installer
        working-directory: ${{ github.workspace }}
        run: makensis installer.nsi
        shell: cmd

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: GenEvolve3D-Installer
          path: ./GenEvolve3D/dist/GenEvolve3D.exe
