name: Build and Package GenEvolve3D Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.9'
      VENV_PATH: D:\a\GenEvolve3D\GenEvolve3D\venv
      PYTHON_PATH: D:\a\GenEvolve3D\GenEvolve3D\src
      INSTALLER_NAME: GenEvolve3D-Installer
      EXECUTABLE_NAME: GenEvolve3D

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create Virtual Environment
        run: python -m venv ${{ env.VENV_PATH }}
        shell: pwsh

      - name: Activate Virtual Environment and Install Dependencies
        run: |
          . ${{ env.VENV_PATH }}\Scripts\Activate
          python -m pip install --upgrade pip
          pip install numpy pyface traits mayavi vtk pyinstaller
        shell: pwsh

      - name: Install Build Tools and NSIS
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          choco install nsis -y
        shell: pwsh

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --paths $env:PYTHON_PATH --name $env:EXECUTABLE_NAME --distpath ${{ github.workspace }} $env:PYTHON_PATH\main.py `
          --hidden-import traitsui --hidden-import pyface.ui.null `
          --hidden-import traitsui.toolkits --hidden-import pyface.ui.qt4 `
          --hidden-import pyface.toolkits.qt4 --hidden-import traitsui.qt4
        shell: pwsh

      - name: Debugging - List Files in Root Directory
        run: |
          echo "Listing files in the GitHub workspace:"
          dir
        shell: cmd
        working-directory: ${{ github.workspace }}

      - name: Package Executable as Installer
        run: |
          echo "Running NSIS to create installer..."
          makensis .github/workflows/installer.nsi
        shell: cmd
        working-directory: ${{ github.workspace }}

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLER_NAME }}
          path: ./.github/workflows/${{ env.EXECUTABLE_NAME }}-Setup.exe
