name: Build and Package GenEvolve3D Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pyface traits mayavi vtk pyinstaller
        shell: pwsh

      - name: Install Visual Studio 2019 Build Tools and NSIS
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          choco install nsis -y
        shell: pwsh

      - name: Build Executable with PyInstaller
  run: |
    pyinstaller --onefile --noconsole --paths src --name GenEvolve3D src/main.py \
    --hidden-import traitsui --hidden-import pyface.ui.null \
    --hidden-import traitsui.toolkits --hidden-import pyface.ui.qt4 \
    --hidden-import pyface.toolkits.qt4 --hidden-import traitsui.qt4
  shell: C:\Program Files\PowerShell\7\pwsh.EXE
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.13\x64


      - name: Package as Installer
        run: |
          makensis .github/workflows/installer.nsi
        shell: cmd
        working-directory: ${{ github.workspace }}

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: GenEvolve3D-Installer
          path: ./.github/workflows/GenEvolve3D-Setup.exe
