name: Build and Package GenEvolve3D Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.9'
      VENV_PATH: D:\a\GenEvolve3D\GenEvolve3D\venv
      PYTHON_PATH: D:\a\GenEvolve3D\GenEvolve3D\src
      INSTALLER_NAME: GenEvolve3D-Installer
      EXECUTABLE_NAME: GenEvolve3D

    steps:
      - name: Reset Workspace
        run: |
          Remove-Item -Path "*" -Recurse -Force -ErrorAction SilentlyContinue
        shell: pwsh
        working-directory: ${{ github.workspace }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv ${{ env.VENV_PATH }}
          . ${{ env.VENV_PATH }}\Scripts\Activate
        shell: pwsh

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pyface traits mayavi vtk pyinstaller
        shell: pwsh

      - name: Install Visual Studio 2019 Build Tools and NSIS
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          choco install nsis -y
        shell: pwsh

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --paths $env:PYTHON_PATH --name $env:EXECUTABLE_NAME $env:PYTHON_PATH\main.py `
          --hidden-import traitsui --hidden-import pyface.ui.null `
          --hidden-import traitsui.toolkits --hidden-import pyface.ui.qt4 `
          --hidden-import pyface.toolkits.qt4 --hidden-import traitsui.qt4
        shell: pwsh

      - name: Move Executable to Root
        run: |
          Move-Item "dist\${{ env.EXECUTABLE_NAME }}.exe" "${{ github.workspace }}"
        shell: pwsh

      - name: List Files in Root Directory (Debugging)
        run: |
          dir
        shell: cmd
        working-directory: ${{ github.workspace }}

      - name: Package as Installer
        run: |
          makensis .github/workflows/installer.nsi
        shell: cmd
        working-directory: ${{ github.workspace }}

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLER_NAME }}
          path: ./.github/workflows/${{ env.EXECUTABLE_NAME }}-Setup.exe
