name: Build and Package GenEvolve3D Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: 3.9
      VENV_PATH: D:\a\GenEvolve3D\GenEvolve3D\venv
      PYTHON_PATH: D:\a\GenEvolve3D\GenEvolve3D\src
      INSTALLER_NAME: GenEvolve3D-Installer
      EXECUTABLE_NAME: GenEvolve3D
      pythonLocation: C:\hostedtoolcache\windows\Python\3.9.13\x64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create Virtual Environment
        run: python -m venv ${{ env.VENV_PATH }}
        shell: pwsh  # Stick with PowerShell for Windows runner

      - name: Activate Virtual Environment and Install Dependencies
        run: |
          . ${{ env.VENV_PATH }}\Scripts\Activate
          python -m pip install --upgrade pip
          pip install numpy pyface traits mayavi vtk cx_Freeze pythreejs
        shell: pwsh  # Stick with PowerShell for Windows runner

      - name: Create cx_Freeze Setup Script
        run: |
          echo "from cx_Freeze import setup, Executable" > setup.py
          echo "setup(name='${{ env.EXECUTABLE_NAME }}', version='0.1', description='GenEvolve3D Application', executables=[Executable('${{ env.PYTHON_PATH }}/main.py')])" >> setup.py
        shell: pwsh  # Stick with PowerShell for Windows runner

      - name: Build Executable with cx_Freeze
        run: |
          . ${{ env.VENV_PATH }}\Scripts\Activate
          python setup.py build
        shell: pwsh  # Stick with PowerShell for Windows runner

      - name: Verify Executable Creation
        run: |
          if (Test-Path "build/exe.win-amd64-3.9/${{ env.EXECUTABLE_NAME }}.exe") {
            echo "Executable found."
          } else {
            echo "Executable not found. Exiting..."
            exit 1
          }
        shell: pwsh  # Stick with PowerShell for Windows runner

      - name: Zip Application Build
        run: |
          Compress-Archive -Path "build/exe.win-amd64-3.9/*" -DestinationPath "${{ env.EXECUTABLE_NAME }}.zip"
        shell: pwsh  # Stick with PowerShell for Windows runner

      - name: Upload Zipped Application
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.EXECUTABLE_NAME }}
          path: ${{ env.EXECUTABLE_NAME }}.zip
          
      - name: Package Executable as Installer
        run: |
          # Create an NSIS installer script
          echo "Creating NSIS installer script..."
          echo '!include "MUI2.nsh"' > installer.nsi
          echo 'Name "GenEvolve3D"' >> installer.nsi
          echo 'OutFile "GenEvolve3D-Setup.exe"' >> installer.nsi
          echo 'InstallDir "$PROGRAMFILES\GenEvolve3D"' >> installer.nsi
          echo 'ShowInstDetails show' >> installer.nsi
          echo 'ShowUnInstDetails show' >> installer.nsi
          echo '!insertmacro MUI_PAGE_WELCOME' >> installer.nsi
          echo '!insertmacro MUI_PAGE_DIRECTORY' >> installer.nsi
          echo '!insertmacro MUI_PAGE_INSTFILES' >> installer.nsi
          echo '!insertmacro MUI_PAGE_FINISH' >> installer.nsi
          echo '!insertmacro MUI_LANGUAGE "English"' >> installer.nsi
          echo 'Section "Install"' >> installer.nsi
          echo '    SetOutPath "$INSTDIR"' >> installer.nsi
          echo "    File 'build/exe.win-amd64-3.9/${{ env.EXECUTABLE_NAME }}.exe'" >> installer.nsi
          echo '    CreateDirectory "$SMPROGRAMS\GenEvolve3D"' >> installer.nsi
          echo '    CreateShortCut "$SMPROGRAMS\GenEvolve3D\GenEvolve3D.lnk" "$INSTDIR\${{ env.EXECUTABLE_NAME }}.exe"' >> installer.nsi
          echo '    WriteUninstaller "$INSTDIR\Uninstall.exe"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          echo 'Section "Uninstall"' >> installer.nsi
          echo '    Delete "$INSTDIR\${{ env.EXECUTABLE_NAME }}.exe"' >> installer.nsi
          echo '    Delete "$SMPROGRAMS\GenEvolve3D\GenEvolve3D.lnk"' >> installer.nsi
          echo '    Delete "$INSTDIR\Uninstall.exe"' >> installer.nsi
          echo '    RMDir "$SMPROGRAMS\GenEvolve3D"' >> installer.nsi
          echo '    RMDir "$INSTDIR"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          # Run NSIS to create the installer
          makensis installer.nsi
        shell: pwsh  # Stick with PowerShell for Windows runner

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLER_NAME }}
          path: GenEvolve3D-Setup.exe
