name: Build and Package GenEvolve3D Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.9'
      # PYTHON_PATH is updated to point to the root of the GitHub workspace
      PYTHON_PATH: D:\a\GenEvolve3D\GenEvolve3D
      INSTALLER_NAME: GenEvolve3D-Installer
      EXECUTABLE_NAME: GenEvolve3D

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pyface traits mayavi vtk pyinstaller
        shell: pwsh

      - name: Install Visual Studio 2019 Build Tools and NSIS
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          choco install nsis -y
        shell: pwsh

      - name: Build Executable with PyInstaller
        run: |
          # Updated the paths in the PyInstaller command
          pyinstaller --onefile --noconsole --paths $env:PYTHON_PATH\src --name $env:EXECUTABLE_NAME $env:PYTHON_PATH\src\main.py `
          --hidden-import traitsui --hidden-import pyface.ui.null `
          --hidden-import traitsui.toolkits --hidden-import pyface.ui.qt4 `
          --hidden-import pyface.toolkits.qt4 --hidden-import traitsui.qt4
        shell: pwsh

      - name: Package as Installer
        run: |
          makensis .github/workflows/installer.nsi
        shell: cmd
        working-directory: ${{ github.workspace }}

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLER_NAME }}
          path: ./.github/workflows/${{ env.EXECUTABLE_NAME }}-Setup.exe
