name: Build and Package GenEvolve3D Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: 3.9
      VENV_PATH: D:/a/GenEvolve3D/GenEvolve3D/venv  # Use forward slashes
      PYTHON_PATH: D:/a/GenEvolve3D/GenEvolve3D/src  # Use forward slashes
      INSTALLER_NAME: GenEvolve3D-Installer
      EXECUTABLE_NAME: GenEvolve3D
      pythonLocation: C:/hostedtoolcache/windows/Python/3.9.13/x64  # Use forward slashes
      DEPENDENCY_CACHE_KEY: 'python-dependencies-${{ hashFiles('**/requirements.txt') }}'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/AppData/Local/pip/Cache  # Use forward slashes
          key: ${{ env.DEPENDENCY_CACHE_KEY }}

      - run: python -m venv ${{ env.VENV_PATH }}
        shell: pwsh

      - run: |
          . ${{ env.VENV_PATH }}/Scripts/Activate
          python -m pip install --upgrade pip
          pip install numpy pyface traits mayavi vtk cx_Freeze pythreejs
        shell: pwsh

      - run: |
          echo "from cx_Freeze import setup, Executable" > setup.py
          echo "setup(name='${{ env.EXECUTABLE_NAME }}', version='0.1', description='GenEvolve3D Application', executables=[Executable('${{ env.PYTHON_PATH }}/main.py')])" >> setup.py
        shell: pwsh

      - run: |
          . ${{ env.VENV_PATH }}/Scripts/Activate
          python setup.py build
        shell: pwsh

      - run: |
          if (Test-Path "build/exe.win-amd64-3.9/${{ env.EXECUTABLE_NAME }}.exe") {
            echo "Executable found."
          } else {
            echo "Executable not found. Exiting..."
            exit 1
          }
        shell: pwsh

      - run: Compress-Archive -Path "build/exe.win-amd64-3.9/*" -DestinationPath "${{ env.EXECUTABLE_NAME }}.zip"
        shell: pwsh

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.EXECUTABLE_NAME }}
          path: ${{ env.EXECUTABLE_NAME }}.zip

      - run: |
          $nsi = @'
          !include "MUI2.nsh"
          Name "GenEvolve3D"
          OutFile "GenEvolve3D-Setup.exe"
          InstallDir "$PROGRAMFILES\GenEvolve3D"
          ShowInstDetails show
          ShowUnInstDetails show
          !insertmacro MUI_PAGE_WELCOME
          !insertmacro MUI_PAGE_DIRECTORY
          !insertmacro MUI_PAGE_INSTFILES
          !insertmacro MUI_PAGE_FINISH
          !insertmacro MUI_LANGUAGE "English"
          Section "Install"
              SetOutPath "$INSTDIR"
              File 'build/exe.win-amd64-3.9/${{ env.EXECUTABLE_NAME }}.exe'
              CreateDirectory "$SMPROGRAMS\GenEvolve3D"
              CreateShortCut "$SMPROGRAMS\GenEvolve3D\GenEvolve3D.lnk" "$INSTDIR\${{ env.EXECUTABLE_NAME }}.exe"
              WriteUninstaller "$INSTDIR\Uninstall.exe"
          SectionEnd
          Section "Uninstall"
              Delete "$INSTDIR\${{ env.EXECUTABLE_NAME }}.exe"
              Delete "$SMPROGRAMS\GenEvolve3D\GenEvolve3D.lnk"
              Delete "$INSTDIR\Uninstall.exe"
              RMDir "$SMPROGRAMS\GenEvolve3D"
              RMDir "$INSTDIR"
          SectionEnd
          '@
          Set-Content -Path installer.nsi -Value $nsi
          makensis installer.nsi
        shell: pwsh

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLER_NAME }}
          path: GenEvolve3D-Setup.exe
