name: Build and Package GENrevolve3D Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.11'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel numpy pygame PyOpenGL PyOpenGL_accelerate
          pip install -r requirements.txt

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --paths src --name GenEvolve3D src/GenEvolve3D.py
        shell: pwsh

      - name: Install NSIS
        run: choco install nsis -y

      - name: Package as Installer
        run: |
          cp ./installer.nsi ${{ github.workspace }}
          makensis ${{ github.workspace }}\installer.nsi
        shell: pwsh

      - name: Upload Packaged Application
        uses: actions/upload-artifact@v2
        with:
          name: GenEvolve3D-Installer
          path: ./GenEvolve3D-Setup.exe

