name: Build and Package GenEvolve3D Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: windows-latest

    env:
      REPO_PATH: "${{ github.workspace }}/repo"
      SRC_PATH: "${{ env.REPO_PATH }}/src"
      BUILD_PATH: "${{ env.SRC_PATH }}/build/exe.win-amd64-3.9"
      EXECUTABLE_PATH: "${{ env.BUILD_PATH }}/main.exe"
      TARGET_PATH: "${{ github.workspace }}/GenEvolve3D"
      NSIS_SCRIPT_PATH: "${{ github.workspace }}/.github/workflows/installer.nsi"
      PYTHON_LOCATION: "C:\hostedtoolcache\windows\Python\3.9.13\x64"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Python Dependencies
        uses: actions/cache@v2
        with:
          path: ~/AppData/Local/pip/Cache
          key: python-dependencies-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create and Activate Python Virtual Environment
        run: |
          python -m venv venv
          .\venv\Scripts\Activate
          python -m pip install --upgrade pip
        shell: pwsh

      - name: Prepare Build Environment
        run: |
          # Ensure the necessary directory structure exists
          if (-not (Test-Path $env.SRC_PATH)) {
            Write-Host "Creating 'src' directory..."
            New-Item -ItemType Directory -Path $env.SRC_PATH -Force
          }
          if (-not (Test-Path $env.BUILD_PATH)) {
            Write-Host "Creating 'build/exe.win-amd64-3.9' directory..."
            New-Item -ItemType Directory -Path $env.BUILD_PATH -Force
          }
          # Copy the repository contents to the src directory
          Write-Host "Copying repository contents to 'src' directory..."
          Get-ChildItem -Recurse "${env.REPO_PATH}/." | ForEach-Object {
            $targetPath = $_.FullName -replace [regex]::Escape($env.REPO_PATH), $env.SRC_PATH
            if (-not (Test-Path $targetPath)) {
              Copy-Item -Path $_.FullName -Destination $targetPath -Force
            }
          }
        shell: pwsh

      - name: Install Dependencies
        run: pip install pyqt5 -r requirements.txt cx_Freeze vispy
        shell: pwsh

      - name: Build Application
        run: |
          python ${{ github.workspace }}/src/setup.py build
          Write-Host "Contents of $env.BUILD_PATH:"
          Get-ChildItem -Path $env.BUILD_PATH -Recurse
        shell: pwsh

      - name: Copy Executable
        run: |
          Write-Host "Checking for executable at: $env.EXECUTABLE_PATH"
          # Use $env.BUILD_PATH in the path to check for the executable
          if (Test-Path $env.EXECUTABLE_PATH) {
            Write-Host "Executable found at $env.EXECUTABLE_PATH"
            Copy-Item $env.EXECUTABLE_PATH -Destination $env.TARGET_PATH -Force
          } else {
            Write-Host "Executable not found at $env.EXECUTABLE_PATH. Exiting..."
            exit 1
          }
        shell: pwsh

      - name: Upload Packaged Application
        if: Test-Path "${{ github.workspace }}/GenEvolve3D.zip"
        uses: actions/upload-artifact@v2
        with:
          name: GenEvolve3D
          path: GenEvolve3D.zip

      - name: Create and Upload Installer
        run: |
          Write-Output "Updating NSIS script"
          if (Test-Path $env.NSIS_SCRIPT_PATH) {
            (Get-Content $env.NSIS_SCRIPT_PATH) | ForEach-Object {
              $_ -replace '\$INSTDIR\\GenEvolve3D\.exe', '\$INSTDIR\\main.exe'
            } | Set-Content $env.NSIS_SCRIPT_PATH
            Write-Output "Running NSIS to create installer"
            Start-Process "C:\Program Files (x86)\NSIS\makensis.exe" -ArgumentList $env.NSIS_SCRIPT_PATH -Wait
          } else {
            Write-Output "NSIS script not found at $env.NSIS_SCRIPT_PATH. Exiting..."
            exit 1
          }
        shell: pwsh

      - name: Upload Installer
        if: Test-Path "${{ github.workspace }}/GenEvolve3D-Setup.exe"
        uses: actions/upload-artifact@v2
        with:
          name: GenEvolve3D-Installer
          path: GenEvolve3D-Setup.exe
