[build-system]
requires = ["setuptools>=42", "wheel", "numpy>=1.21.2,<1.22"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
name = "GENrevolve3D"
version = "1.0.0"
description = "A 3D Evolution Simulation Application"
long_description = "file: README.md"
long_description_content_type = "text/markdown"
url = "https://github.com/HermiTech-L3C/GENrevolve3D"
author = "HermiTech L3C"
author_email = "Reel0112358.13@proton.me"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["simulation", "evolution", "3D", "learning"]
packages = find:
package_dir = {"": "src"}
include_package_data = True
install_requires = [
    "numpy>=1.21.2,<1.22",
    "pandas>=1.2,<1.3",
    "matplotlib>=3.4,<3.5",
    "scikit-learn>=0.24,<0.25",
    "PyQt5>=5.15,<5.16",
    "mayavi>=4.7,<4.8",
    # Add any other project-specific dependencies here
]
extras_require = {
    "dev": ["pytest>=6.0,<7", "mypy", "flake8", "black"]
}
python_requires = ">=3.7"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    .eggs
    | .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.flake8]
max-line-length = 120
exclude = .tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules

[tool.isort]
profile = "black"

[tool.mypy]
files = "src"
ignore_missing_imports = false 

[tool.pyinstaller]
main_script = "src/Main.py"
onefile = true
noconsole = true
additional_hooks_dir = "pyinstaller_hooks"
