name: Build and Package GENrevolve3D Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-package:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Wheel and NumPy
      run: pip install wheel numpy

    - name: Install Mayavi
      run: pip install mayavi

    - name: Install Other Python dependencies
      run: pip install -r requirements.txt

   # - name: Run tests
    #  run: pytest

    - name: Build Executable with PyInstaller
      run: pyinstaller --onefile --noconsole --paths src ./src/Main.py

    - name: Install NSIS
      run: choco install nsis

    - name: Package as Installer
      run: makensis .github/workflows/install.nsi

    - name: Upload Packaged Application
      uses: actions/upload-artifact@v2
      with:
        name: GENrevolve3D-Installer
        path: ./dist/GENrevolve3D-Setup.exe
