name: Build and Package GENrevolve3D Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: 3.9
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Check and Reinstall Key Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy scipy scikit-learn

      - name: Locate DLLs for NumPy, SciPy, and Scikit-Learn
        run: |
          import os
          import numpy
          import scipy
          import sklearn

          for package in [numpy, scipy, sklearn]:
              package_path = os.path.dirname(package.__file__)
              print(f"{package.__name__} is installed at: {package_path}")

              for root, dirs, files in os.walk(package_path):
                  for file in files:
                      if file.endswith('.dll'):
                          print(os.path.join(root, file))
        shell: python

      - name: Install NSIS
        run: choco install nsis

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --additional-hooks-dir=.github/workflows/hooks --paths src --name Main src/Main.py

      - name: Package as Installer
        run: makensis .github/workflows/install.nsi

      - name: Upload Packaged Application
        uses: actions/upload-artifact@v2
        with:
          name: GENrevolve3D-Installer
          path: .\dist\Main.exe
