name: Build and Package GENrevolve3D Application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: 3.9
    steps:
uses: actions/checkout@v2
name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install numpy scipy scikit-learn
          pip install -r requirements.txt

name: Verify NumPy Installation
        run: |
          python -c "import numpy; print(numpy.__version__); print(numpy.get_include())"

name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --additional-hooks-dir=.github/workflows/hooks --paths src --name Main src/Main.py
        env:
          NUMPY_PATH: ${{ steps.install-numpy.outputs.numpy-path }}

name: Install NSIS
        run: choco install nsis

name: Package as Installer
        run: |
          makensis .github/workflows/install.nsi

name: Upload Packaged Application
        uses: actions/upload-artifact@v2
        with:
          name: GENrevolve3D-Installer
          path: .\dist\Main.exe
